export interface BathymetryLayer {
  id: string;
  name: string;
  depthRange: string;
  formation: string;
  geologicalSignificance: string;
  relationToIndianOcean: string;
  relationToKumariKandamClaim: string;
}

export const BATHYMETRY_LAYERS: BathymetryLayer[] = [
  {
    id: 'bathy-shelf',
    name: 'Continental Shelf',
    depthRange: '0–150 m',
    formation: 'The gently sloping, submerged edge of a continent, built from sediment eroded off the adjacent landmass.',
    geologicalSignificance: 'Shelves are made of true continental (granitic/sedimentary) crust and were exposed as dry land repeatedly during Ice Age low sea stands.',
    relationToIndianOcean: 'The Gulf of Mannar / Palk Strait shelf between India and Sri Lanka, and the Wadge Bank south of Kanyakumari, are real continental shelf features.',
    relationToKumariKandamClaim: 'Genuine shelf flooding after the Last Glacial Maximum is the most credible geological kernel behind south Indian "land lost to the sea" traditions — but a shelf a few tens of kilometres wide is not a continent-sized landmass.',
  },
  {
    id: 'bathy-slope',
    name: 'Continental Slope',
    depthRange: '150–3,000 m',
    formation: 'The steep transition zone where continental crust thins and gives way to oceanic crust.',
    geologicalSignificance: 'Marks the true geological edge of a continent; beyond it, crust composition changes fundamentally from granite to basalt.',
    relationToIndianOcean: 'South of the Indian shelf, the slope drops quickly into the deep basins of the central Indian Ocean.',
    relationToKumariKandamClaim: 'No large-scale continental slope structure exists south of Kanyakumari consistent with a sunken continent reaching toward Madagascar or Antarctica.',
  },
  {
    id: 'bathy-abyssal',
    name: 'Abyssal Plain',
    depthRange: '3,000–6,000 m',
    formation: 'Vast, flat expanses of ocean floor blanketed by fine sediment, underlain by basaltic oceanic crust.',
    geologicalSignificance: 'Oceanic crust here is geologically young (formed by seafloor spreading) and dense — it has never been dry, continental land.',
    relationToIndianOcean: 'The Central Indian Basin and Wharton Basin are classic abyssal plains flanking the mid-ocean ridges.',
    relationToKumariKandamClaim: 'Directly contradicts the popular claim: the seafloor between India and Antarctica is young basaltic crust, not a drowned granite continent.',
  },
  {
    id: 'bathy-ridge',
    name: 'Mid-Ocean Ridge',
    depthRange: 'Crest ~2,000–3,000 m (rises above surrounding basins)',
    formation: 'A long undersea mountain chain where tectonic plates diverge and new oceanic crust is continuously generated by upwelling magma.',
    geologicalSignificance: 'Evidence of active plate divergence, not a static or sinking landmass.',
    relationToIndianOcean: 'The Central Indian Ridge, Southwest Indian Ridge, and Southeast Indian Ridge meet at the Rodrigues Triple Junction.',
    relationToKumariKandamClaim: 'Ridges are spreading centers building new crust — the opposite process of a continent sinking; they show the Indian Ocean growing, not swallowing land.',
  },
  {
    id: 'bathy-plateau',
    name: 'Oceanic Plateau',
    depthRange: 'Highly variable, often 1,000–3,000 m above surrounding seafloor',
    formation: 'Thickened oceanic or transitional crust formed by large volcanic outpourings (large igneous provinces) or stranded continental fragments.',
    geologicalSignificance: 'Some plateaus (like the Kerguelen Plateau) contain continental-affinity rock, making them genuinely unusual, "almost-continent" features.',
    relationToIndianOcean: 'Kerguelen Plateau, Mascarene Plateau, and the Ninety East Ridge are major Indian Ocean plateaus/ridges.',
    relationToKumariKandamClaim: 'These plateaus are real submerged crustal anomalies — but they date to tens of millions of years before any human presence, and are geographically distant from the claimed Kumari Kandam location.',
  },
  {
    id: 'bathy-fracture',
    name: 'Fracture Zones',
    depthRange: 'Trough depths often 4,000–6,000 m',
    formation: 'Long linear scars where transform faults offset segments of mid-ocean ridges.',
    geologicalSignificance: 'Record the direction and rate of past plate motion, used to reconstruct how India, Madagascar, and Antarctica separated.',
    relationToIndianOcean: 'Numerous fracture zones cross-cut the Central and Southwest Indian ridges, used by geologists to date the India–Madagascar rift at ~88 million years ago.',
    relationToKumariKandamClaim: 'Fracture-zone reconstructions are part of the hard evidence that India separated from Madagascar by slow rifting, not sudden catastrophic sinking.',
  },
  {
    id: 'bathy-seamounts',
    name: 'Seamounts',
    depthRange: 'Summits from a few hundred to several thousand metres below sea level',
    formation: 'Extinct or active submarine volcanoes, often formed over hotspots as a plate moves over a stationary magma source.',
    geologicalSignificance: 'Seamount chains (like the Chagos-Laccadive Ridge) trace the track of the Réunion hotspot beneath the drifting Indian plate.',
    relationToIndianOcean: 'The Chagos-Laccadive Ridge, Ninety East Ridge, and Comorin Ridge are volcanic seamount/ridge chains south of India.',
    relationToKumariKandamClaim: 'These are volcanic in origin, not sunken pieces of a former Tamil homeland; their ages (tens of millions of years) predate any human civilization by a vast margin.',
  },
  {
    id: 'bathy-microcontinents',
    name: 'Microcontinents',
    depthRange: 'Buried under lava, typically 1,000–1,500 m below sea level (e.g. beneath Mauritius)',
    formation: 'Small fragments of continental crust left stranded in ocean basins when larger continents rifted apart.',
    geologicalSignificance: 'Confirmed by anomalously old zircon crystals found in young volcanic rock, revealing buried Precambrian continental material.',
    relationToIndianOcean: 'Mauritia (beneath Mauritius and the Mascarene Plateau) and the Seychelles granitic bank are confirmed Indian Ocean microcontinents.',
    relationToKumariKandamClaim: 'Microcontinents are genuine "lost" slivers of continental crust — but they are geological debris from the Gondwana breakup roughly 60–85 million years ago, with no connection to a historical or Holocene-era Tamil civilization.',
  },
  {
    id: 'bathy-banks',
    name: 'Submerged Banks',
    depthRange: 'Typically 20–200 m',
    formation: 'Shallow, elevated areas of the seafloor, often relict coral platforms or shelf remnants, that stayed shallow after full submergence.',
    geologicalSignificance: 'Some banks preserve drowned coral reefs and beach ridges that record former, lower sea levels.',
    relationToIndianOcean: 'The Wadge Bank off Kanyakumari and the Laccadive/Maldive banks are examples within Indian Ocean waters.',
    relationToKumariKandamClaim: 'Banks like Wadge Bank are cited by some popular writers as "remnants of Kumari Kandam"; geologists treat them instead as ordinary shelf/reef features shaped by sea-level change, with no evidence of prior habitation or continental scale.',
  },
];
